apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvcName }}
  labels:
    app: {{ .Values.postgres.serviceName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvcStorage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.serviceName }}
  labels:
    app: {{ .Values.postgres.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.serviceName }}
    spec:
      containers:
      - name: {{ .Values.postgres.serviceName }}
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.postgresUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.postgresDB }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvcName}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  labels:
    app: {{ .Values.postgres.serviceName }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.servicePort }}
    targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.serviceName }}